### PR TITLE
Fix update crash after code cleanup

### LINKED ISSUE #61: Data corruption/Crash with CONFLICT DO UPDATE statement
On CONFLICT DO UPDATE statement on tde table, corrupt the data and sometimes even crash the server.

Below is the reproducable test case.
```
DROP TABLE  if exists UNIQUE_TBL;
CREATE TABLE UNIQUE_TBL (i int UNIQUE, t text) using pg_tde;
INSERT INTO UNIQUE_TBL VALUES (1, 'one');
INSERT INTO UNIQUE_TBL VALUES (2, 'two');
INSERT INTO UNIQUE_TBL VALUES (1, 'three'); --ERROR
INSERT INTO UNIQUE_TBL (t) VALUES ('seven');
INSERT INTO UNIQUE_TBL VALUES (5, 'five-upsert-insert') ON CONFLICT (i) DO UPDATE SET t = 'five-upsert-update';
INSERT INTO UNIQUE_TBL VALUES (6, 'six-upsert-insert') ON CONFLICT (i) DO UPDATE SET t = 'six-upsert-update';
SELECT * FROM UNIQUE_TBL;
-- should fail
INSERT INTO UNIQUE_TBL VALUES (1, 'a'), (2, 'b'), (2, 'b') ON CONFLICT (i) DO UPDATE SET t = 'fails';
SELECT * FROM UNIQUE_TBL;
```

### LINKED ISSUE #62: Update the partitioned table with pg_tde as default table access method crash the server
Update the partitioned table with pg_tde, as the default table access method crashes the server

Reproducible test case
Note: Occasionally the test case runs without  a problem, and requires two or three tries to reproduce the crash 
```
SET default_table_access_method TO 'pg_tde';
drop table if exists mlparted_tab cascade;
drop table if exists some_tab cascade;
drop table if exists some_tab_child cascade;

create table some_tab (a int) ;
insert into some_tab values (0); 
create table some_tab_child () inherits (some_tab);
insert into some_tab_child values (1);

create table mlparted_tab (a int, b char, c text) partition by list (a) ; 
create table mlparted_tab_part1 partition of mlparted_tab for values in (1); 
create table mlparted_tab_part2 partition of mlparted_tab for values in (2) partition by list (b); 
create table mlparted_tab_part3 partition of mlparted_tab for values in (3); 
create table mlparted_tab_part2a partition of mlparted_tab_part2 for values in ('a');
create table mlparted_tab_part2b partition of mlparted_tab_part2 for values in ('b');
insert into mlparted_tab values (1, 'a'), (2, 'a'), (2, 'b'), (3, 'a');
 
UPDATE mlparted_tab mlp set c = 'xxx'
 FROM
   (SELECT a from some_tab union all select a+1 from some_tab) ss (a)
 WHERE (mlp.a = ss.a and mlp.b = 'b') or mlp.a = 3; 

select tableoid::regclass::text as relname, mlparted_tab.* from mlparted_tab order by 1,2; 
 
```

### LINKED ISSUE #64: Triggers on views over tde table causes a crash
The following test case produces a crash
```
--
-- 2 -- Test triggers on a join view
--
SET default_table_access_method TO 'pg_tde';

DROP VIEW IF EXISTS city_view CASCADE;
DROP TABLE IF exists country_table CASCADE;
DROP TABLE IF exists city_table cascade;

 CREATE TABLE country_table (
     country_id        serial primary key,
     country_name    text unique not null,
     continent        text not null
 ) using pg_tde;
 
 INSERT INTO country_table (country_name, continent)
     VALUES ('Japan', 'Asia'),
            ('UK', 'Europe'),
            ('USA', 'North America')
     RETURNING *;
 
 CREATE TABLE city_table (
     city_id        serial primary key,
     city_name    text not null,
     population    bigint, 
     country_id    int references country_table
 ) using pg_tde;
 
 CREATE VIEW city_view AS
     SELECT city_id, city_name, population, country_name, continent
     FROM city_table ci
     LEFT JOIN country_table co ON co.country_id = ci.country_id;
 
CREATE OR REPLACE FUNCTION city_insert() RETURNS trigger LANGUAGE plpgsql AS $$
 declare
     ctry_id int;
 begin
     if NEW.country_name IS NOT NULL then
         SELECT country_id, continent INTO ctry_id, NEW.continent
             FROM country_table WHERE country_name = NEW.country_name;
         if NOT FOUND then 
             raise exception 'No such country: "%"', NEW.country_name;
         end if;
     else
         NEW.continent := NULL;
     end if;
 
     if NEW.city_id IS NOT NULL then
         INSERT INTO city_table
             VALUES(NEW.city_id, NEW.city_name, NEW.population, ctry_id);
     else
         INSERT INTO city_table(city_name, population, country_id)
             VALUES(NEW.city_name, NEW.population, ctry_id)
             RETURNING city_id INTO NEW.city_id;
     end if;
 
     RETURN NEW;
 end;
 $$;

  CREATE TRIGGER city_insert_trig INSTEAD OF INSERT ON city_view
 FOR EACH ROW EXECUTE PROCEDURE city_insert();
 
 CREATE OR REPLACE FUNCTION city_delete() RETURNS trigger LANGUAGE plpgsql AS $$
 begin
     DELETE FROM city_table WHERE city_id = OLD.city_id;
     if NOT FOUND then RETURN NULL; end if;
     RETURN OLD;
 end;
 $$;
 
 CREATE TRIGGER city_delete_trig INSTEAD OF DELETE ON city_view
 FOR EACH ROW EXECUTE PROCEDURE city_delete();
 
 CREATE OR REPLACE FUNCTION city_update() RETURNS trigger LANGUAGE plpgsql AS $$
 declare
     ctry_id int;
 begin
     if NEW.country_name IS DISTINCT FROM OLD.country_name then
         SELECT country_id, continent INTO ctry_id, NEW.continent
             FROM country_table WHERE country_name = NEW.country_name;
         if NOT FOUND then
             raise exception 'No such country: "%"', NEW.country_name;
         end if;
 
         UPDATE city_table SET city_name = NEW.city_name,
                               population = NEW.population,
                               country_id = ctry_id
             WHERE city_id = OLD.city_id;
     else
         UPDATE city_table SET city_name = NEW.city_name,
                               population = NEW.population
             WHERE city_id = OLD.city_id;
         NEW.continent := OLD.continent;
     end if;
 
     if NOT FOUND then RETURN NULL; end if;
     RETURN NEW;
 end;
 $$;

 CREATE TRIGGER city_update_trig INSTEAD OF UPDATE ON city_view
 FOR EACH ROW EXECUTE PROCEDURE city_update();
 
-- INSERT .. RETURNING
 INSERT INTO city_view(city_name) VALUES('Tokyo') RETURNING *;
 INSERT INTO city_view(city_name, population) VALUES('London', 7556900) RETURNING *;
 INSERT INTO city_view(city_name, country_name) VALUES('Washington DC', 'USA') RETURNING *;
 INSERT INTO city_view(city_id, city_name) VALUES(123456, 'New York') RETURNING *;
 INSERT INTO city_view VALUES(234567, 'Birmingham', 1016800, 'UK', 'EU') RETURNING *;
 
 -- UPDATE .. RETURNING
 UPDATE city_view SET country_name = 'Japon' WHERE city_name = 'Tokyo'; -- error
 UPDATE city_view SET country_name = 'Japan' WHERE city_name = 'Takyo'; -- no match
 UPDATE city_view SET country_name = 'Japan' WHERE city_name = 'Tokyo' RETURNING *; -- OK
 
 UPDATE city_view SET population = 13010279 WHERE city_name = 'Tokyo' RETURNING *;
 UPDATE city_view SET country_name = 'UK' WHERE city_name = 'New York' RETURNING *;
 UPDATE city_view SET country_name = 'USA', population = 8391881 WHERE city_name = 'New York' RETURNING *;
 UPDATE city_view SET continent = 'EU' WHERE continent = 'Europe' RETURNING *;
 UPDATE city_view v1 SET country_name = v2.country_name FROM city_view v2
     WHERE v2.city_name = 'Birmingham' AND v1.city_name = 'London' RETURNING *;
 
 -- DELETE .. RETURNING
 DELETE FROM city_view WHERE city_name = 'Birmingham' RETURNING *;
 

```

### PR DESCRIPTION
**Pull request by dutow**
Issue: the code cleanup introduced in PR #52 modified the original tuple in the update method instead of decrypting the tuple data into a copy. This caused data curruption crashes in some test.

Fix: reintroduce the missing palloc to the update method.

Fixes #61
Fixes #62
Fixes #64

### CODE REVIEW

File: src/access/pg_tdeam.c [hunk 1]
```diff
@@ -3112,9 +3114,24 @@ pg_tde_update(Relation relation, ItemPointer otid, HeapTuple newtup,
 	oldtup.t_len = ItemIdGetLength(lp);
 	oldtup.t_self = *otid;
 	/* decrypt the old tuple */
-	PG_TDE_DECRYPT_TUPLE(BufferGetBlockNumber(buffer), page, &oldtup, &oldtup,
+	{
+		MemoryContext oldContext;
+		char* new_ptr = NULL;
+		oldContext = MemoryContextSwitchTo(CurTransactionContext);
+		new_ptr = palloc(oldtup.t_len);
+		MemoryContextSwitchTo(oldContext);
```
Comment (dAdAbird) [inline src/access/pg_tdeam.c:3122]:
```suggestion
		char* new_ptr = NULL;
		new_ptr = MemoryContextAlloc(CurTransactionContext, oldtup.t_len);
```
Really nitpicking but to me its looks cleaner while doing the same job.

**Review by dAdAbird — APPROVED** [review]
LGTM
It also fixes https://github.com/Percona-Lab/postgres-tde-ext/issues/61 issues with aborted transactions with updates. I can create a PR with regressions tests for those after merging this PR

**Comment by codeforall** [comment]
This PR broke the Update statements.
https://github.com/Percona-Lab/postgres-tde-ext/issues/68
